### ISSUE TITLE
HLScrollNode clips content but not gestures

### ISSUE THREAD

**Issue by btraut** [hilogames/HLSpriteKit#10]
I ended up writing my own version of your scroll node before I discovered HLSpriteKit and it looks like you ran into the same issue I did: SKCropNodes crop content, but they still intercept taps where that content would otherwise be drawn.

[I've asked on StackOverflow](http://stackoverflow.com/questions/39313883/how-do-i-prevent-touches-from-hitting-hidden-content-in-skcropnode) how to prevent this, but it doesn't seem like SpriteKit gives us the tools. I suspect it has something to do with drawing and tap handling happening in different parts of the system. That in mind, my version of the scroll node still checked to see if a tap/pan/pinch/etc landed inside or outside the SKCropNode's visible content. If outside, it passed the event onto the next deepest node.

Does all that make sense? Does it sound reasonable? I could try to retro-fit it into HLScene.

**Comment by btraut** [comment]
Actually, on second thought, I should probably rescind my offer to integrate this myself. I'm happy to share my code (it's actually posted in the StackOverflow article linked above), but it doesn't look like there is full support implemented for content clipping in HLScrollNode right now anyway, and it's more than I can bite off for now.

**Comment by karlvoskuil** [comment]
Yes, totally reasonable.  Good thinking.

One part of this is easy: The `HLScrollNode` knows about its size and can stop responding to pans and pinches outside the scroll area.  I've pushed 8aac95b to address this.

The harder part is what your code was addressing: If I'm a content node, how do I know when I've been cropped, and stop responding to gestures in the cropped area?  I think there are two different ways to think about this:
1. _This issue with crops is due to bad implementations of `nodesAtPoint` and/or `containsPoint` and/or `frame` in SpriteKit, and they should fix it. The good news is that it's not a problem for most apps or most nodes._ From this point of view, we handle problems in a one-off kind of way: We can provide your code (walk the hierarchy looking for crops) as a public method for any node to use for itself; this would work for gesture-targets in the HLSpriteKit ecosystem, but also for responders in the `UIResponder` ecosystem (`touchesBegan` and friends). But also we encourage dumb workarounds: For instance, I haven't had troubles with this issue because all my scroll nodes scroll their content offscreen (of the device).  Or: In my app I could make dumb border nodes around the scroll node, with a higher `zPosition` (or sibling order), in order to intercept touches before the cropped content does.  Annoying, but effective for all versions of SpriteKit now and in the future.
2. _In `HLSpriteKit`, however, we already have a centralized gesture-handler in `HLScene`, so we can fix this problem ourselves for **all** nodes in the scene._ Here we would use code very similar to yours; it would go in HLScene's `gestureRecognizer:shouldReceiveTouch:`. It would also have the same limitations you mention. It might have to change with future SpriteKit changes.  It will add computation time to the gesture handler, so perhaps it should be optional.  If there are nodes in the scene using the `UIResponder` touch interface, they would not get this fix.

What do you think?

**Comment by karlvoskuil** [comment]
By the way, `HLScrollNode` does support content clipping, but it's off by default; property `contentClipped` must be set true.

**Comment by btraut** [comment]
But the property only specifies a public getter, right? The setter isn't exposed. Or am I only running into this because I'm using it with Swift through a bridging header?

**Comment by btraut** [comment]
The fix looks good. As for your ideas above -- I had intended on doing both 1 and 2 in my own implementation. Make the method public to everyone (via extension/category) and also use it in my scene which acted as the dispatcher for all gestures.

But all that said, I wonder if this is just too specific to my app. After asking a couple questions about scrolling containers in StackOverflow and also scouring what's out there, it seems that people just aren't very interested in them. Maybe people usually blend UIKit with SpriteKit so they don't need to do scrolling in their games? Maybe SpriteKit is still too new to be considered a heavyweight and most people move to cocos2d/Unity/etc for bigger games? Maybe people just design non-scrolling UIs? I just have a hard time believing this is the case. After all, all I want for my game is a way to pan/zoom around the world map in one panel and scroll through a list of items to use in another panel -- pretty common paradigm for a game, but in order to accomplish it I've had to write those panels myself along with gestures, inertial scrolling, etc.

If I really am a severe minority, it may not be worth doing anything in HLSpriteKit. Just let people implement their own solutions like me, or live with other "dumb" solutions like you recommended. Better to keep the bloat out of the framework rather than committing to support it.

**Comment by karlvoskuil** [comment]
> But the property only specifies a public getter, right? The setter isn't exposed. Or am I only running into this because I'm using it with Swift through a bridging header?

It should have a setter. Could be the bridging header.  It's possible you're being tricked by the Objective-C declaration:

```
@property (nonatomic, getter=isContentClipped) BOOL contentClipped;
```

The getter has a special name, but the setter still is created with its default name (`setContentClipped`).

**Comment by karlvoskuil** [comment]
> After all, all I want for my game is a way to pan/zoom around the world map in one panel and scroll through a list of items to use in another panel -- pretty common paradigm for a game, but in order to accomplish it I've had to write those panels myself along with gestures, inertial scrolling, etc.

I have all kinds of thoughts here.
- Totally a side note, but: I should do inertial scrolling in `HLScrollNode`.
- I have also noticed the lack of reusable SpriteKit stuff! Maybe studios keep it in-house.
- Maybe scrolling math is considered too easy to justify building a reusable mechanism, especially since it's so tightly bound to the gesture handler (controller).  It was only when I started copy-and-pasting pinch/zoom code a second time that I really thought to myself, "I should put this in a reusable object."
- In fact, even with my supposedly modular gesture-target system, I still often end up rewriting the gesture-handling code for my scroll nodes in the controller object (and just set scrollNode.contentOffset from the controller).

> If I really am a severe minority, it may not be worth doing anything in HLSpriteKit. Just let people implement their own solutions like me, or live with other "dumb" solutions like you recommended. Better to keep the bloat out of the framework rather than committing to support it.

Okay.  I'm 51% convinced to leave it out of `HLScene`'s gesture handler, for now.

I'd totally be in favor of including it as a non-member public function somewhere.  That doesn't bloat much, and it might be useful.  Perhaps I could leave it to your instinct: Would it be a nice addition to `HLSpriteKit`?  If it were me, I'd think I'd write it as a method returning a boolean for is-cropped at a certain point (even though that loses the efficiency of `testedNodes` when searching up a hierarchy).  And (as you say) as an `SKNode` extension.  For file location, maybe `SKNode+HLGestureTarget.h` even though the code isn't specific to gesture-targeting; or maybe a new file `SKNode+HLNodeAdditions.h`.  For method name, I'd like to get the word "crop" in there since it's all about the crop node and not strictly about visibility.  It would be nice to get "mask frame (or bounds)" in there, too, so that it's fully honest about what it is testing.

```
- (BOOL)hlAncestorCropMaskFrameContainsPoint:(CGPoint)point

- (BOOL)hlCropMaskFrameContainsPoint:(CGPoint)point

- (BOOL)hlCropMaskFrameExcludesPoint:(CGPoint)point

- (BOOL)hlAncestorMaskFrameCropsPoint:(CGPoint)point

- (BOOL)hlCropsPoint:(CGPoint)point
```

Hard to get a name that feels right.

Other random notes:
- The passed point would be expected to already be in the coordinate system of the node.
- The algorithm would need to account for the mask node's `anchorPoint`, I think, when testing bounds.

**Comment by karlvoskuil** [comment]
Closing this for now.  Reopen if there is action to be taken.
