### ISSUE TITLE
Can you enhance the example project?

### ISSUE THREAD

**Issue by Sweeper777** [hilogames/HLSpriteKit#12]
In the example project, I expect to see the usage of each of the features. But I feel like they are scattered everywhere in the file. Can you group the code with `#pragma mark` so that it is clear which is which?

At the moment, if I want to know how to use `HLTableLayoutManager`, I need to search for keywords in the file. And they are scattered everywhere. It's really hard to find.

Alternatively, can you show the usage of one feature in one scene?

**Comment by karlvoskuil** [comment]
Thanks for the request!

It's a totally reasonable request, but sounds like too much work, at the moment.  :)

My theory of the example project is not that it demonstrates every feature, and not that it's a tutorial, but that it shows the way actual code would look when using HLSpriteKit.  For example, the code using `HLTableLayoutManager` is spread throughout `HL_createContent` in the file `HLCatalogScene.m`—but it's spread out like that because that's the way you would use a table layout manager.

I should also say: the primary documentation for each component should be in its header file.  Probably that doesn't help very much, but, for example, documentation for properties of `HLTableLayoutManager` (say, `columnWidths`) can be found in [the .h file](https://github.com/hilogames/HLSpriteKit/blob/master/HLSpriteKit/HLTableLayoutManager.h#L139) or on [Cocoadocs](http://cocoadocs.org/docsets/HLSpriteKit/1.2.0/Classes/HLTableLayoutManager.html#//api/name/columnWidths).

Thanks again for the feedback, and I'll keep it in mind next time I'm adding to the Example project.
