### ISSUE TITLE
Does HLGridNode.setContent(_:) resets all the nodes in the grid node?

### ISSUE THREAD

**Issue by Sweeper777** [hilogames/HLSpriteKit#13]
Let's say I have a grid node with 200 squares. And there are about 100 squares already with content in it. The contents are just single `SKSpriteNode`s with textures. Now every second, I want the content of at most 8 squares to change. By "change", I mean to change from having no content to having a single `SKSpriteNode` as content, or the other way around.

To do this, I need to call `setContent(_:)` every second. The parameter is an array that I maintained.

The question is that does `setContent(_:)`
- remove all the contents in the grid node, then add each one from the array in? or;
- only reset those squares that changed?

I need to know this because I'm afraid that if it does the former, it would waste a lot of time and memory since many of the squares' contents will remain unchanged after `setContent(_:)` and they will be reset anyway.

I don't want to use `setContent(_:forSquare:)` because it is too tedious...

**Comment by karlvoskuil** [comment]
`setContent` removes each old content node before setting the new one from the array.

Thoughts:
1. This won't waste memory, because the nodes aren't copied.
2. There will be wasted time, though, as the pointer from the parent is unset and then set again.  There will also be time wasted as certain properties are set again unnecessarily (highlight, enabled, node name, `zPosition`, etc).
3. However, the time wasted probably won't be noticeable on the scale of 200 nodes every second: there won't be any new allocations or other more time-consuming operations.  It's worth trying as-is.
4. If the wasted time is noticeable, or if your scale becomes more demanding, then I think it would be reasonable to do a `isEqual` or pointer-equivalence shortcut in `setContent`.  It will still go through the 200 nodes, but it will skip certain operations when the new node is the same as the old node.

**Comment by karlvoskuil** [comment]
Something like this:

```
diff --git a/HLSpriteKit/HLItemNode.m b/HLSpriteKit/HLItemNode.m
index d790f5b..728c25d 100644
--- a/HLSpriteKit/HLItemNode.m
+++ b/HLSpriteKit/HLItemNode.m
@@ -88,6 +88,16 @@ - (void)setContent:(SKNode *)contentNode
 - (void)setContent:(SKNode *)contentNode contentDidSetEnabled:(BOOL *)contentDidSetEnabled contentDidSetHighlight:(BOOL *)contentDidSetHighlight
 {
   SKNode *oldContentNode = [self childNodeWithName:@"content"];
+  *contentDidSetEnabled = NO;
+  *contentDidSetHighlight = NO;
+  // note: Doing an isEqual check seems like too much overhead for not much benefit;
+  // there's not really that much code below that we'd be short-circuiting.  But doing
+  // a quick pointer check seems nice to support the use-case where the owner has 100
+  // content nodes in an array and keeps setting-content on all of them whenever any
+  // of them changes.
+  if (oldContentNode == contentNode) {
+    return;
+  }
```

**Comment by karlvoskuil** [comment]
Pushed 492ea7e590e7787468bb2f826eee101395c20d1d.

Thanks for the thought!  I'll close this hoping my solution is good enough, but feel free to reopen if you have any followups!
