### ISSUE TITLE
Passing nil to gridNode.setContent results in error

### ISSUE THREAD

**Issue by Sweeper777** [hilogames/HLSpriteKit#14]
In my grid node, I want to leave all but one square empty. So I created a 2D array of my model, and mapped it to a 1D array. After that, I mapped the 1D array again to get the `SKSpriteNode` objects from my mode.

```
var modelObjs: [[Model?]]

init(...) {
    // created a 2D array filled with nils. The array is 10x20
    let repeating: [Model?] = [Model?](repeating: nil, count: 20)
    models = [[Model?]](repeating: repeating, count: 10)
}

func syncModel() {
    someGridNode.setContent(models.flatMap { $0 }.map { $0?.node })
}
```

When I call `syncModel`, this error occurs:

> [_SwiftValue setName:]: unrecognized selector sent to instance 0x60000024fff0

When I change the line in `syncModel` to this:

```
someGridNode.setContent(models.flatMap { $0 }.map { $0?.node ?? SKSpriteNode(color: UIColor.black, size: CGSize.zero) })
```

No errors occur.

So I suspect that the array I pass into `setContent` must no contain `nil`. But why? Why not make it so that if `setContent` sees a nil in the array, it removes the content from the square?

**Comment by karlvoskuil** [comment]
So, I have a idea, but I don't know enough Swift to be able to provide the correct solution.

In short, `setContent` takes an `NSArray`, and `NSArray` cannot contain `nil`.  Instead, an "empty" `NSArray` element is supposed to be a reference to the singleton object `[NSNull null]` (or in Swift, `NSNull()`).  (See [Apple documentation](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/NumbersandValues/Articles/Null.html) for more information about `NSNull` in collection objects.)

If that's the problem, then we need to fix it in your Swift code . . . and I don't know the best way to do that.  It looks to me like you're using a built-in Swift array with an optional type, and that's getting bridged to an `NSArray` at the method call.  I would have expected the bridging to Objective-C to replace optional types with `NSNull` . . . or maybe not? Maybe the problem is that the optional type is preserved in the `NSArray` but `setContent` does not expect an optional type, and so does not unwrap it? No matter what, I would have expected some kind of warning from your compiler.

Can you explicitly use an `NSMutableArray` for the result of your `flapMap` call?  Then you'd get better warnings, I bet.

**Comment by Sweeper777** [comment]
I tried to use

```
someGridNode.setContent(models.flatMap { $0 }.map { $0?.node ?? NSNull() })
```

And no errors occured!

Can you add this as a note in README so that swift users won't get confused?

**Comment by karlvoskuil** [comment]
Oh good!

A note in the README might help someone, but this is a problem not for HLSpriteKit but for any framework interface that takes an `NSArray` as a parameter.

That said: if there's a way I can rewrite `setContent` to be more friendly to Swift callers, I'd be happy to do so.  It's unfortunate I'm not writing Swift yet myself, so I don't notice these things.
