### ISSUE TITLE
HLToolbarNode.hideAnimated removes toolbar node from parent

### ISSUE THREAD

**Issue by Relequestual** [hilogames/HLSpriteKit#15]
I was looking to hide and show the toolbar when dragging an object in my world (to give more space on a mobile device).

I would expect to be able to use the hide and the show function provided, but the hide function removes the toolbar from the parent node, while the show function does not require a node to add the toolbar back to.

It feels like the hide action shouldn't remove the node from the parent. If I want to remove it from the parent also, then I could do that after, or add another param to the hide function; a boolean to remove from parent node or not. I had to dig through the code to work this out.

P.S. my game is progressing slowwwwly, but progress is neat =]

**Comment by Relequestual** [comment]
On another note, I allow for the scale to remain the same. What if I want to keep the scale the same and just move it off screen and then back on screen again? I think I'll have to write my own functions for doing this, although the existing functions are mightly helpful! Thanks.

**Comment by karlvoskuil** [comment]
Yes, good points.  The toolbar was the first component I wrote, and when I look at the show/hide stuff, it looks naive to me.  I thought at the time that different toolbar owners would want to reuse the same show/hide functionality, but now I realize that showing/hiding should be in the owner's domain, because only the owner/controller knows how to do it.  Should it be a slide or a zoom or a fade?  Where does it start, where does it end, and should it remove from parent?  Should the animation use an easing function so it appears to accelerate?

I should also have realized this just because of the pairing of addChild and removeFromParent: Like you say, if the owner adds the child, then it should be responsible for removing it from parent, too.

Also: A certain controller probably wants to show/hide all of its components in the same way, for instance, everything fades instead of sliding.  It will use the same fade-in/fade-out code for all its components, so the code belongs in the controller, not the components.

Anyway.  I'm rambling.

So yeah, I'd say write the functions in your controller.  But also, I'd be happy to add `removeFromParent` boolean option to the `hideAnimated:` function.

Or actually . . . I know this wasn't your intention, but now I'm thinking I need to delete the show and hide functions completely.  They are misleading.  :)

Thanks!

**Comment by Relequestual** [comment]
Thanks for taking the time to reply!
Initially I actually just relied on intelesense and changed the boolean property. I would say that you could make a show and hide function which simply sets that boolean. As for animation, I personally found it helpful to see how it COULD be done, but I agree it is constraining in the way you've done it (but as you say, your first component, and we all learn!). 

Your framework has been pretty helful to me, so it's really appreciated! Currently a simple hide and show is all I need, and I can work out niceties later.

**Comment by karlvoskuil** [comment]
Pushed 65fd000c060f5aae883be89439a01c7f4cdf5854 to remove show/hide.
I think any show/hide functions generic enough to be used by callers will be too trivial to include.
So yeah, not what you asked for . . . but I consider it progress!  Thanks.
