### ISSUE TITLE
Unable to layout SKLabelNodes using HLTableLayout

### ISSUE THREAD

**Issue by Sweeper777** [hilogames/HLSpriteKit#17]
I want to lay out two label nodes using the code below:

```
    let anchorPoint = NSValue(cgPoint: CGPoint(x: 0.5, y: 0.5))
    let scoreboardNode = SKSpriteNode(color: UIColor.yellow.withAlphaComponent(0.77), size: CGSize(width: 700, height: 180))
    scoreboardNode.zPosition = 1001
    let scoreboardTableLayout = HLTableLayoutManager(columnCount: 1, columnWidths: [(0.0)], columnAnchorPoints: [anchorPoint], rowHeights: [(0.0)])!
    scoreboardTableLayout.rowSeparator = 15
    scoreboardNode.hlSetLayoutManager(scoreboardTableLayout)

    let scoreLabel = SKLabelNode(text: "SCORE:            0")
    scoreLabel.fontSize = 61
    scoreLabel.fontName = "Courier-Bold"
    scoreLabel.horizontalAlignmentMode = .center
    scoreLabel.fontColor = UIColor.black
    scoreboardNode.addChild(scoreLabel)

    let bestScoreLabel = SKLabelNode(text: "BEST:             0")
    bestScoreLabel.fontSize = 61
    bestScoreLabel.horizontalAlignmentMode = .center
    bestScoreLabel.fontName = "Courier-Bold"
    bestScoreLabel.fontColor = UIColor.black
    scoreboardNode.addChild(bestScoreLabel)

    scoreboardNode.hlLayoutChildren()

    self.addChild(scoreboardNode)
```

I basically created two label nodes, and called `hlLayoutChildren`. But it appears like this:

<img width="598" alt="screen shot 2016-10-12 at 4 56 11 pm" src="https://cloud.githubusercontent.com/assets/13585047/19317475/0b960ac0-909d-11e6-9716-ac942a21e1e8.png">

The two labels are stuck together!

After some testing, I found out that if I set `tableLayout.rowSeparator` to a larger number, the distance between the two labels becomes larger.

**Comment by karlvoskuil** [comment]
Interesting! The row height `0.0` is supposed to automatically size the row to the labels in it, but it looks like it's failing to find the heights of the labels.  In fact, it looks like it's considering the height of the labels to be 0...so then the only thing separating the rows is the row separator.

IIRC the height is based on the label's frame.size.height.  I'll look into it and get back to you!

A workaround in the meantime would be not to rely on "auto" but instead specify a row height of `[(61.0)]` so that the rows are correctly sized; then you wouldn't need to specify such a big row separator.

**Comment by karlvoskuil** [comment]
Thank you for the bug report!  Very clear and easy to reproduce.

It only reproduces in iOS10: Apple exposed an undocumented `size` selector in `SKNode`, which returns 0 for SKLabelNode.

Pushed cf0e3ad8c71eb66e19b3876f2a1e49d108f3e4ea to work around it in HLSpriteKit.

Thanks again.
