### ISSUE TITLE
Can you lower the deployment target version to 8.0?

### ISSUE THREAD

**Issue by Sweeper777** [hilogames/HLSpriteKit#19]
I'm installing the pod this way:

```
pod 'HLSpriteKit', :git => 'https://github.com/hilogames/HLSpriteKit.git'
```

When I `pod install`, cocoapods says

```
Specs satisfying the `HLSpriteKit (from `https://github.com/hilogames/HLSpriteKit.git`)` dependency were found, but they required a higher minimum deployment target.
```

I want my app to support iOS 8 so that more people can download it. I don't think this pod uses anything from iOS 9 or 10, right? Can you lower the deployment target?

**Comment by karlvoskuil** [comment]
I think 8.4 is a good compromise.  For these reasons:
1. I had some troubles in 8.0 that were fixed in a 8.1 or 8.2, but to be honest, now I'm forgetting exactly what.  Maybe the `removeFromParent` crash?  Or something with crop nodes?  Can't remember.
2. 8.4 still supports iOS8, but requires the latest minor version in order to get all the bug fixes and features.
3. Apple aggressively deprecates old versions, and 8.0 is no longer supported in the current Xcode.  I've read that I can download a previous version of Xcode in order to test it, but I'd rather not.

**Comment by Sweeper777** [comment]
Ok, I see. Thank yoU!

**Comment by karlvoskuil** [comment]
Thank you!  I've really been appreciating your feedback and ideas; keep them coming.

**Comment by Sweeper777** [comment]
Apparently now I cannot submit bundles targeted at iOS 8.4:

<img width="515" alt="screen shot 2016-10-28 at 11 04 22 am" src="https://cloud.githubusercontent.com/assets/13585047/19803072/9d35e12c-9cfe-11e6-9ec4-daeed7d02446.png">

I guess I have to change my deployment version to 9.0 after all...

**Comment by karlvoskuil** [comment]
Hm. I guess 8.4 is not a good compromise after all.

Okay, I think it would be reasonable for me to lower my deployment minimum to 8.0 and hope there aren't many problems.  Sorry for the runaround.  I hope to have it done in the next hour or so.

**Comment by karlvoskuil** [comment]
Okay, version 1.4.0 has a lowered deployment to 8.0.  Thanks again.
