### ISSUE TITLE
HLScrollNode

### ISSUE THREAD

**Issue by phpmaple** [hilogames/HLSpriteKit#6]
When I use HLScrollNode, size not control scroll's board

**Comment by karlvoskuil** [comment]
Yeah, I didn't implement cropping as part of HLScrollNode: the size of the scroll node determines the math relating to the scrolling and positioning of contents, but it doesn't crop the contents to that size.

I'd be happy to work on that if you're interested!  I'll probably get to it in the next week or so.  In the meantime, you can always put the HLScrollNode inside your own SKCropNode . . . but yeah, it seems like the UIScrollNode should have that built in.

Thanks for the report!

**Comment by karlvoskuil** [comment]
Pushed 5db9040eac5fae56bbd0387d3eeffd5991d2a50d to master. Give it a try and let me know if it works for you: set property `contentClipped` to `YES` in order to enable clipping.

If you're using this via CocoaPods, update to use master like this:

  pod 'HLSpriteKit', :git => 'https://github.com/hilogames/HLSpriteKit.git'

**Comment by karlvoskuil** [comment]
Reopening; the new clipping code doesn't work for non-default `anchorPoint` of `UIScrollNode`. I hope to have a fix soon.

**Comment by karlvoskuil** [comment]
Oh, uh, that was easier than I thought it would be.  Pushed d6aadc7337b4d9060eb37502b6ad9de759092fa7.

**Comment by phpmaple** [comment]
I find HLScrollNode's contentsize is not equal to my set contentsize

**Comment by phpmaple** [comment]
sometimes larger than or less than my set contentsize

**Comment by karlvoskuil** [comment]
Okay.  How can I reproduce the bug?
