### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by btraut** [hilogames/HLSpriteKit#8]
Any plans to support SpriteKit on Mac? I started trying to port myself, but there's some decisions that need to be made around gesture support given that it's somewhat different on the Mac. I'd love to use some of the utility nodes such as HLTileNode even without the gesture support.

**Comment by karlvoskuil** [comment]
If you're interested, I'm interested. I've not even done a Hello World for OS X, but I'll try it out tomorrow or the next day and see what can be done for a first iteration.

**Comment by karlvoskuil** [comment]
Update: I've got a stripped down version of HLSpriteKit compiling under OS X, but need to go through and test everything thoroughly.  I'm creating an example application for OS X as part of the Cocoapods example.  When everything's roughly working, I'll do some basic interaction support for OS X (as well as `UIResponder` interface under iOS, I think).

**Comment by karlvoskuil** [comment]
Pushed 1.2.0 with support for compilation under iOS and macOS platforms.
Now I will go back and add some interaction features for macOS.

**Comment by karlvoskuil** [comment]
Pushed e2f0b3348 to master with basic `NSResponder` interaction support.
Closed for now; feel free to reopen (or open separate issue) for feedback, bug reports, or feature requests!

**Comment by btraut** [comment]
Thanks!

**Comment by btraut** [comment]
@karlvoskuil: Finally had a chance to dig a little deeper into this.

Your changes look great, and will definitely help me cut down on some duplicate code between my stuff and HLSpriteKit.

One thing that I'm still craving is the gesture recognizer routing system. I'm sure you'd agree that it's frustrating that SpriteKit expects you to register all GestureRecognizers at the SKView level, and that problem still exists on the Mac. I think I'm going to take another run at porting HLGestureTarget stuff to Mac as well. If I get stuck, I'll post here. Otherwise, expect a pull request in the next few days.

Thanks again!

**Comment by btraut** [comment]
I'm making great progress but I hit my first snag. Apparently NSGestureRecognizer only supports one target/action. We need multiple.

It's pretty easy to collect a bunch of target/action pairs into an array and then call them all on each trigger, but where do we set up that array? My first attempt here is by adding a category for NSGestureRecognizer that adds a `addTarget:selector:` method and an instance variable for storing them (via [this method](http://stackoverflow.com/questions/4146183/instance-variables-for-objective-c-categories)), but it feels pretty gross. I'm also reeeeeally rusty when it comes to Objective-C and this sort of voodoo might be beyond me.

Thoughts? Suggestions?

**Comment by btraut** [comment]
Okay, I've worked through everything and [I have a reeeeeeally rough draft](https://github.com/btraut/HLSpriteKit/tree/macOSGestures). As in, it builds but I haven't run it yet. I'll continue to work on it tomorrow, but for now you can check it out if you like.

**Comment by karlvoskuil** [comment]
Wow, that's fantastic!  I didn't even know there was an `NSGestureRecognizer`; for some reason I thought it was all `NSResponder`.  We share the same bias for using gesture recognizers.

I'm already running out of time today, so I might have to continue tomorrow, but here are my thoughts so far:
1. Your plan for the multiple target/action stuff makes perfect sense. If your way works, then let's do it, and we can always change it later if we think it's too ugly. A reasonable alternative would be to store target/action arrays in the `HLScene`: it owns the gesture recognizers, and so it can own the associated targets/actions.
2. From a quick look, I can't see where gesture targets get the chance to add themselves to a `UIGestureRecognizer` or `NSGestureRecognizer`. The old way: the UIGestureRecognizer begins recognizing a gesture and calls its delegate, `HLScene`, to see if that's okay.  The delegate then finds all available gesture targets in the scene, using hit-testing, and asks them if they are interested in the gesture.  So that delegate method is the method in HLScene.m that you commented out: `gestureRecognizer:shouldReceiveTouch:`; the NS equivalent, I think, would be `gestureRecognizer:shouldAttemptToRecognizeWithEvent:`. In particular, that method calls each gesture target's `addToGesture:firstTouchSceneLocation:isInside:`.
3. When I was adding the UIResponder and NSResponder stuff, I had a hard time with a naming problem: Is it a "tap" if it's for macOS?  In `HLGridNode`, for instance, there is a delegate callback `gridNode:didTapSquare:`.  Do I need to make an equivalent `gridNode:didClickSquare:` for macOS?  Could I come up with a generic [UX-centric](http://ux.stackexchange.com/questions/37963/what-word-can-be-used-to-mean-either-click-or-tap) name and use it for either taps or clicks: `gridNode:didActivateSquare:` (or select or press)?  Anyway, I decided that I wasn't allowed to use "tap" when I meant "click", because macOS might have a touch-sensitive surface and be able to respond to both taps **and** clicks, in which case it would be confusing if I were calling clicks "taps."  The reason I'm mentioning this is because of `HLTapGestureTarget`: Rather than changing it to work for both iOS and macOS, I'm thinking we probably need a separate `HLClickGestureTarget` or else a generic name like `HLActivateGestureTarget`.
4. By the way, I'm working on a separate diff to (supposedly) clarify some of the gesture target stuff.  (Purely FYI, you probably don't need to know this, but just in case it changes anything for you: The breaking change is that I want to stop calling `registerDescendent` for each gesture target added to a scene.  I've decided that it's both misleading and unnecessary.  The real purpose of calling a method in the scene is to add shared gesture recognizers to the HLScene, and so that's what the method should be called: `needSharedGestureRecognizersForNode:`.  That matches with the other `needSharedGestureRecognizers:` method that already exists for the same purpose.)
5. I was trying to figure out where to put typedef stuff like your `HLGestureRecognizer`.  I'm thinking it belongs in `HLGestureTarget.h`, and I want to see if you agree.  My reasoning: 1) You need the typedef for `HLGestureRecognizer` if and only if you are including `HLGestureTarget.h`; 2) `HLTypeDef.h` doesn't sound related to gesture targets; 3) There isn't a need for a generic typedefs file for all of HLSpriteKit, because, say If there is another similar typedef, like something so that SKLabelNode and HLMultilineLabelNode can be used identically, then it probably belongs in HLMultilineLabelNode, and the owner doesn't need to include the typdef for gesture targets too.

One final note: Now that I've caught your vision, I'd be happy to contribute to this change.  You've done the heavy lifting with the NSGestureRecognizer thing.  I'd be happy to do some of the integration work if that seems tedious to you—for instance, I could work on the changes to HLGestureTarget and HLScene.

**Comment by karlvoskuil** [comment]
Side note: I've pushed my `HLGestureTarget` changes, but I'm afraid they'll cause all kinds of conflicts with your commits.  So for now I've pushed them to branch [no-more-register-gesture-targets](https://github.com/hilogames/HLSpriteKit/tree/no-more-register-gesture-targets).  If you hand off the HLGestureTarget and HLScene work to me, then I'll base master on my changes; otherwise I'll wait for you, and rebase on your work.

**Comment by btraut** [comment]
> Your plan for the multiple target/action stuff makes perfect sense. If your way works, then let's do it, and we can always change it later if we think it's too ugly.

I just jumped back into this, so let me test and give a stronger recommendation one way or the other. I'm particularly nervous about the hacky way I'm calling the provided selectors because there's basically no type-safety and it's unclear how it will react if the user gives it a bad selector. I'll get back to you on this one.

> So that delegate method is the method in HLScene.m that you commented out: gestureRecognizer:shouldReceiveTouch:; the NS equivalent, I think, would be gestureRecognizer:shouldAttemptToRecognizeWithEvent:. In particular, that method calls each gesture target's addToGesture:firstTouchSceneLocation:isInside:.

Ohhh! I was confused by this, perhaps because I encountered it at 3am. I hadn't realized that this was a UIGestureRecognizerDelegate method. Yeah, it shouldn't be commented out, and the Mac equivalent should be added.

> I was trying to figure out where to put typedef stuff like your HLGestureRecognizer. I'm thinking it belongs in HLGestureTarget.h, and I want to see if you agree.

Totally reasonable. I separated it into its own file at the beginning under the assumption that I'd end up with a lot more shared typedefs, but it ended up being easier just using #ifdefs to split platform-specific code rather than using typedefs within the same code.

> One final note: Now that I've caught your vision, I'd be happy to contribute to this change. You've done the heavy lifting with the NSGestureRecognizer thing. I'd be happy to do some of the integration work if that seems tedious to you—for instance, I could work on the changes to HLGestureTarget and HLScene.

That would be great! Like I said, I feel like I'm a bit out of my depth here. I just wanted to make a cross-platform game, and I never expected to be modifying a framework. :) So what's the easiest way to share? Should I just add a pull request to bring my branch over to your repo, and you take it from there?

**Comment by btraut** [comment]
Alright, put some more time into my NSGestureRecognizer category and I'm pretty sure I've got it working properly. See latest commit:

https://github.com/btraut/HLSpriteKit/commit/a8760c03e2c224024b773ffc3fb446b86555e2c3

I'll set up a pull request so you can take over. Let me know how else I can help.

**Comment by btraut** [comment]
Oh, hmm. Looks like I can't submit a pull request against a new branch. Either you can do the pulling yourself or I can submit a pull request after you create a branch for me. I'd do the work myself, but I'd feel a lot more comfortable if you worked through the merge with your latest `HLGestureTarget` changes.

**Comment by karlvoskuil** [comment]
Okay, got it!  I've pulled it into my local repository, and I'll integrate it and push it back out when I've got something to show.  Next couple days, I think.

**Comment by karlvoskuil** [comment]
Pushed c31f6e47ac8d934a17b14c0293ee6bcbfe3790c6.

It . . . appears to work!

I thought I was going to do two commits: a squashed version of your pull request, and then my changes.  But my changes ended up being just tweaks, no real substance, and so I just squashed them in with your commit and pushed it under your name.  Hope that's okay!

Current thoughts:
1. I think I _love_ this gesture forwarding under macOS.  Rewriting the example project for mac was a pleasure.  Thank you so much for introducing me to `NSGestureRecognizer`!
2. Aw nuts I see I put a typo in the CHANGELOG.  Fixing...
3. One of my tweaks was to continue distinguishing between "click" and "tap".  As you can see [in the example project](https://github.com/hilogames/HLSpriteKit/blob/master/Example/Shared/HLCatalogScene.m#L120), that leads to lots of trivial-looking conditional compilation for common gestures.  I'd definitely be willing to revisit this decision.  I think "click" and "tap" should always be distinct—but I'm open to having HLSpriteKit nodes, by default, to deal with higher-level concepts like "select" or "activate."
4. I'm about to add some trackpad support for pinch gestures on HLScrollNode under macOS.  I expect it will go well.
5. I check compilation under the xcodeproj in the top-level directory, but I'm still a Carthage noob and so I don't know if there's more I should do to test it.  Let me know if you see anything obvious.

**Comment by btraut** [comment]
Great job, Karl! It's going to take me a couple of days to try all the new stuff out but it all looks good to me from a high level.

**Comment by karlvoskuil** [comment]
Closing for now!  Feel free to reopen (or open a new issue) with feedback.
